# Generated by Django 2.2.7 on 2019-11-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='yeet'),
            preserve_default=False,
        ),
    ]
